services:
  wordpress:
    image: wordpress:latest
    container_name: wp-wordpress
    ports:
      - "${WP_PORT:-8080}:80"
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=${MYSQL_USER:-wordpress}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD:-changeme}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE:-wordpress}
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - db
    networks:
      - wordpress_network

  db:
    image: mysql:8.0
    container_name: wp-mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
      - MYSQL_USER=${MYSQL_USER:-wordpress}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-changeme}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    networks:
      - wordpress_network

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: wp-phpmyadmin
    ports:
      - "${PMA_PORT:-8081}:80"
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
    depends_on:
      - db
    networks:
      - wordpress_network

volumes:
  wordpress_data:
  mysql_data:

networks:
  wordpress_network:
    driver: bridge